import PropTypes from "prop-types";
import { db } from "../firebase.js";
import { setDoc, doc, deleteDoc, getDocs, collection, query, where, onSnapshot } from "firebase/firestore";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import ProjectFormSub1 from "./ProjectFormSub1.js";
import ProjectFormSub2 from "./ProjectFormSub2.js";
import ProjectFormSub3 from "./ProjectFormSub3.js";
import ProjectFormSub4 from "./ProjectFormSub4.js";
import ProjectFormSub5 from "./ProjectFormSub5.js";
import ProjectFormSub6 from "./ProjectFormSub6.js";
import ProjectFormSub7 from "./ProjectFormSub7.js";
import FeedbackCommentsDelays from "./FeedbackCommentsDelays.js";
import QuotingForm from "./QuotingForm.js";
import ProjectFormProgressReport from "./ProjectFormProgressReport.js";
import ProjectFormDetailedCheckList from "./ProjectFormDetailedCheckList.js";
import { templates } from "./ProjectFormTemplates.js";
import { useDragging } from "./hooks/useDragging.js";

// Single consolidated React import (add useCallback here; include all your needed hooks)
import { useState, useEffect, useRef, useMemo, useCallback } from "react";

// lodash import (keep as is)
import { throttle } from 'lodash';

function ProjectForm({ 
  onClose, 
  project: initialProject, 
  processes, 
  personnel, 
  customers,
  onSave,
  isArchived = false
}) {
  const isReadOnly = isArchived || initialProject?.status === "archived";

    const { formRef, position, startDrag, onDrag, stopDrag } = useDragging();
  const [project, setProject] = useState({
	  
    id: initialProject?.id || "",
    orderNumber: initialProject?.orderNumber || "",
    quoteNumber: initialProject?.quoteNumber || "",
    orderNumberDate: initialProject?.orderNumberDate || "",
    workSheetNo: initialProject?.workSheetNo || "",
    salesRep: initialProject?.salesRep || "",
    customer: initialProject?.customer || "",
    jobDescription: initialProject?.jobDescription || "",
    dueDate: initialProject?.dueDate || "",
    actualCompletionDate: initialProject?.actualCompletionDate || "",
    stages: initialProject?.stages || [],
    selectedTemplate: initialProject?.selectedTemplate || "Select Stage Template",
    selectedMachine: initialProject?.selectedMachine || "",
    isSalesRepInputActive: initialProject?.isSalesRepInputActive || false,
    poDate: initialProject?.poDate || "",
    fixtureDesign: initialProject?.fixtureDesign || [],
    manufacturingParts: initialProject?.manufacturingParts || [],
    buyOuts: initialProject?.buyOuts || [],
    fixtureAssembly: initialProject?.fixtureAssembly || [],
  });
  const [orderPrefix, setOrderPrefix] = useState(
    project.orderNumber?.startsWith("CUST.EPR") ? "CUST.EPR" :
    project.orderNumber?.startsWith("EXPT.EPR") ? "EXPT.EPR" :
    project.orderNumber?.startsWith("COD") ? "COD" :
    project.orderNumber?.startsWith("CUST.GO-AHEAD") || project.orderNumber?.startsWith("CUST.GA") ? "CUST.GA" :
    project.orderNumber?.startsWith("EXPT.MAC") ? "EXPT.MAC" :
    "PO"
  );
  const [orderNumber, setOrderNumber] = useState(
    project.orderNumber?.replace(/^(PO|CUST\.EPR|EXPT\.EPR|COD|CUST\.GO-AHEAD|CUST\.GA|EXPT\.MAC)/, "") || ""
  );
  const [isOrderNumberAutoGenerated, setIsOrderNumberAutoGenerated] = useState(false);
  const [quoteNumber, setQuoteNumber] = useState(project.quoteNumber || "");
  const [orderNumberDate, setOrderNumberDate] = useState(project.orderNumberDate || "");
  const [workSheetNo, setWorkSheetNo] = useState(project.workSheetNo?.replace("WS", "") || "");
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  useEffect(() => {
    console.log("ProjectForm workSheetNo state:", workSheetNo, "project.workSheetNo:", project?.workSheetNo);
  }, [workSheetNo, project]);
  const [salesRep, setSalesRep] = useState(project.salesRep || "");
  const [customer, setCustomer] = useState(project.customer || "");
  const [jobDescription, setJobDescription] = useState(project.jobDescription || "");
  const [currentDate] = useState(new Date().toISOString().split("T")[0]);
  const [dueDate, setDueDate] = useState(project.dueDate || "");
  const [firstDueDate, setFirstDueDate] = useState(project.dueDate || null);
  const [actualCompletionDate, setActualCompletionDate] = useState(
    project.stages?.find((stage) =>
      stage.process === "Sign Delivery Book" || stage.process === "Site Instr. Signed Off"
    )?.startingDate?.split("T")[0] || project.actualCompletionDate?.split("T")[0] || ""
  );
  const [stages, setStages] = useState(() => {
    if (!project.stages || (project.stages.length === 2 && project.stages.every((stage) =>
      ["Quote Auth&Submit", "Invoiced"].includes(stage.process)))) {
      return [];
    }
    return project.stages.map((stage) => ({
      ...stage,
      cell: personnel.find((p) => p.name === stage.responsible)?.cell || "",
      startingDate: stage.startingDate || "",
      stageDuration: stage.stageDuration || "TBD",
      plannedHrs: stage.plannedHrs || "",
      completionDate: stage.completionDate || "",
      status: stage.process === "Sign Delivery Book" && stage.status !== "Completed"
        ? "Insert Del. No. Below" : stage.status || "Not Started",
      deliveryBookNo: stage.deliveryBookNo || "",
      machine: stage.machine || (stage.process === "Wire Cutting" ? "OP110-WIRECUT.FANUC" :
        stage.process === "Grinding" ? "OP330-CINCINATTI.HORZ.GRINDER" : "")
    }));
  });
  const [signDeliveryBookNo, setSignDeliveryBookNo] = useState(
    project.stages?.find((stage) => stage.process === "Sign Delivery Book")?.deliveryBookNo || ""
  );
  const [siteInstrSignedOffNo, setSiteInstrSignedOffNo] = useState(
    project.stages?.find((stage) => stage.process === "Site Instr. Signed Off")?.deliveryBookNo || ""
  );
  const [signDeliveryBookEntered, setSignDeliveryBookEntered] = useState(!!signDeliveryBookNo);
  const [siteInstrSignedOffEntered, setSiteInstrSignedOffEntered] = useState(!!siteInstrSignedOffNo);
  const [pulseSignDeliveryBook, setPulseSignDeliveryBook] = useState(false);
  const [pulseSiteInstrSignedOff, setPulseSiteInstrSignedOff] = useState(false);
  const [selectedPersonnel, setSelectedPersonnel] = useState("Accounts");
  const [isSalesRepInputActive, setIsSalesRepInputActive] = useState(project.isSalesRepInputActive || false);
  const [showStages, setShowStages] = useState(
    project.stages && (project.stages.length > 2 || project.stages.some(
      (stage) => !["Quote Auth&Submit", "Invoiced"].includes(stage.process)))
  );
  const [showFeedbackModal, setShowFeedbackModal] = useState(false);
  const [showQuotingForm, setShowQuotingForm] = useState(false);
  const [messageCount, setMessageCount] = useState(0);
  const [selectedTemplate, setSelectedTemplate] = useState(project.selectedTemplate || inferTemplate(stages));
  const [validationError, setValidationError] = useState("");

  const addStageButtonRef = useRef(null);

  const originalId = project.id;
  const [machines, setMachines] = useState([]);

  const [selectedMachine, setSelectedMachine] = useState(project.selectedMachine || "");
  const [selectedProgressReport, setSelectedProgressReport] = useState("Select Progress Report");
  const [isProgressReportEnabled, setIsProgressReportEnabled] = useState(true);

  const [tempProjectId] = useState(
    `TEMPORARY_ID_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
  );

  const projectId = orderNumber ? `${orderPrefix}${orderNumber}` : tempProjectId;

  // === UNSAVED CHANGES - FINAL FIX ===
  useEffect(() => {
    setHasUnsavedChanges(false);
  }, [projectId]);   // reset when form opens with a real project

useEffect(() => {
  if (isReadOnly) return;
  setHasUnsavedChanges(true);
}, [orderNumber, orderPrefix, quoteNumber, workSheetNo, salesRep, 
    customer, jobDescription, dueDate, selectedTemplate, stages, isReadOnly]);

  // red X warning
  useEffect(() => {
    const handleBeforeUnload = (e) => {
      if (hasUnsavedChanges) {
        e.preventDefault();
        e.returnValue = "You have unsaved changes.\n\nSave and Close";
        return "You have unsaved changes.\n\nSave and Close";
      }
    };
    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => window.removeEventListener("beforeunload", handleBeforeUnload);
  }, [hasUnsavedChanges]);

  useEffect(() => {
    console.log("ProjectForm mounted with projectId:", projectId);
    if (projectId.startsWith("TEMPORARY_ID")) {
      console.warn("Using TEMPORARY_ID for projectId. orderNumber:", orderNumber, "orderPrefix:", orderPrefix);
    }
    return () => console.log("ProjectForm unmounted");
  }, [projectId, orderNumber, orderPrefix]);

  useEffect(() => {
    if (!orderNumber || orderNumber.trim() === "") {
      setValidationError("PO Number is Required");
    } else {
      setValidationError("");
    }
  }, [orderNumber]);

  const inferTemplate = (stages) => {
    if (!stages || stages.length <= 2) return "Select Stage Template";
    const stageProcesses = stages.map((s) => {
      if (!s || typeof s === "string") {
        return typeof s === "string" ? s.toLowerCase() : "";
      }
      if (typeof s.process === "string") {
        return s.process.toLowerCase();
      }
      console.warn("Invalid stage value:", s);
      return "";
    });
    const templateMap = {
      "1 - Workshop Work": [
        "quote auth&submit",
        "material ordered",
        "material received",
        "turning",
        "quality control",
        "milling",
        "quality control",
        "wire cutting",
        "quality control",
        "grinding",
        "quality control",
        "plating_blacken",
        "quality control",
        "sign delivery book",
        "invoiced",
      ],
      "2 - Site Work": [
        "timing plan",
        "quote auth&submit",
        "material ordered",
        "material received",
        "site installation",
        "test installation",
        "site instr. signed off",
        "invoiced",
      ],
      "3 - Fabrication Work": [
        "quote auth&submit",
        "material ordered",
        "material received",
        "dwg.apr.fab",
        "fabrication",
        "quality control",
        "painting",
        "quality control",
        "sign delivery book",
        "invoiced",
      ],
      "4 - Buy & Supply": [
        "quote auth&submit",
        "material ordered",
        "material received",
        "supply",
        "sign delivery book",
        "invoiced",
      ],
      "5 - Breakdown": ["quote auth&submit", "sign delivery book", "invoiced"],
      "6 - Machine Repairs": [
        "quotes submit",
        "quote auth&submit",
        "mechanical repairs",
        "electrical repairs",
        "electronic repairs",
        "test machine",
        "sign invoice",
        "invoiced",
      ],
      "7 - Shut Down Work": [
        "shut work",
        "site instr. signed off",
        "invoiced",
      ],
      "8 - Transportation": [
        "delivery note-customer",
        "quote auth&submit",
        "sign delivery book",
        "invoiced",
      ],
    "9 - Stock Supplied": [
      "supply",
      "sign delivery book",
      "invoiced",
    ],
    "10 - Fitting": [
      "disassemble",
      "quote auth&submit",
      "material ordered",
      "material received",
      "assembly",
      "quality control",
      "sign delivery book",
      "invoiced",
    ],
    };
    for (const [template, processes] of Object.entries(templateMap)) {
      if (
        stageProcesses.length === processes.length &&
        stageProcesses.every((p, i) => p === processes[i].toLowerCase())
      ) {
        return template;
      }
    }
    return "Select Stage Template";
  };

  const stageProgressPercentage = useMemo(() => {
    if (!stages || !Array.isArray(stages) || stages.length === 0) return 0;
    const completedStages = stages.filter((stage) =>
      ["Completed", "Drawing Reviewed", "Completed: QC Pass"].includes(stage.status)
    ).length;
    return (completedStages / stages.length) * 100;
  }, [stages]);

  const fetchMessageAsync = async () => {
    console.log("fetchMessageAsync called with projectId:", projectId);
    if (!projectId || projectId === "PO" || projectId.startsWith("TEMPORARY_ID")) {
      setMessageCount(0);
      console.log("New project detected, setting messageCount to 0");
      return;
    }
    try {
      const feedbackQuery = query(
        collection(db, "feedback"),
        where("projectId", "==", projectId)
      );
      const feedbackSnapshot = await getDocs(feedbackQuery);
      console.log(`Message count for projectId ${projectId}: ${feedbackSnapshot.size}`);
      if (feedbackSnapshot.empty) {
        console.log(`No feedback documents found for projectId '${projectId}'`);
      } else {
        feedbackSnapshot.forEach((doc) =>
          console.log(`Feedback document for projectId '${projectId}': id=${doc.id}, data=`, doc.data())
        );
      }
      setMessageCount(feedbackSnapshot.size);
    } catch (error) {
      console.error("Error fetching message count:", error);
      setMessageCount(0);
    }
  };

  useEffect(() => {
    console.log("ProjectForm mounted with projectId:", projectId);
    fetchMessageAsync();
  }, [projectId]);

  useEffect(() => {
    const checkAwaitingPO = async () => {
      try {
        const feedbackQuery = query(collection(db, "feedback"), where("message", "==", "awaiting PO"));
        const snapshot = await getDocs(feedbackQuery);
        console.log("Awaiting PO entries in Firestore:", snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })));
      } catch (error) {
        console.error("Error querying awaiting PO entries:", error);
      }
    };
    checkAwaitingPO();
  }, []);

  useEffect(() => {
    setStages((prevStages) =>
      prevStages.map((stage) => ({
        ...stage,
        cell: personnel.find((p) => p.name === stage.responsible)?.cell || stage.cell,
      }))
    );
  }, [personnel]);

  useEffect(() => {
    const deliveryStage = stages.find(
      (stage) => stage.process === "Sign Delivery Book" || stage.process === "Site Instr. Signed Off"
    );
    const date = deliveryStage?.startingDate?.split("T")[0] || project.actualCompletionDate?.split("T")[0] || "";
    setActualCompletionDate(date);
  }, [stages, project.actualCompletionDate]);

  useEffect(() => {
    if (!firstDueDate && dueDate) setFirstDueDate(dueDate);
  }, [dueDate, firstDueDate]);

  useEffect(() => {
    if (salesRep && stages[0]?.process === "Quote Auth&Submit") {
      setStages((prevStages) => {
        const newStages = [...prevStages];
        if (
          !project ||
          (!newStages[0].responsible && newStages[0].process === "Quote Auth&Submit")
        ) {
          const person = personnel.find((p) => p.name === salesRep);
          newStages[0] = {
            ...newStages[0],
            responsible: salesRep,
            cell: person?.cell || "",
          };
        }
        return newStages;
      });
    }
  }, [salesRep, personnel, project]);

  useEffect(() => {
    const unsubMachines = onSnapshot(collection(db, "machines"), (snapshot) => {
      setMachines(
        snapshot.docs
          .map((doc) => ({ id: doc.id, ...doc.data() }))
          .sort((a, b) => {
            const matchA = a.name.match(/\d+/);
            const matchB = b.name.match(/\d+/);
            if (matchA && matchB) {
              const numA = parseInt(matchA[0], 10);
              const numB = parseInt(matchB[0], 10);
              return numA - numB;
            }
            return a.name.localeCompare(b.name);
          })
      );
    });
    return () => unsubMachines();
  }, []);

  const formatPhoneNumber = (number) =>
    number
      ? `+27${number.replace(/\D/g, "").slice(number.startsWith("0") ? 1 : 0)}`
      : "";

  const getWhatsAppLink = (number, message) =>
    `https://wa.me/${formatPhoneNumber(number)}?text=${encodeURIComponent(message)}`;

  const triggerWhatsApp = (repName) => {
    const person = personnel.find((p) => p.name === repName);
    if (person?.cell && orderNumber) {
      const message = `Hi ${repName}, you've been assigned as Sales Rep for ${orderPrefix}${orderNumber}. Job: ${jobDescription}. Customer: ${customer}. You may proceed with your first process stage. Thanks`;
      window.open(getWhatsAppLink(person.cell, message), "_blank");
    }
  };

  const calculateDuration = (index, stages) => {
    const stage = stages[index];
    if (!stage.startingDate || !stage.completionDate) return "TBD";
    const end = new Date(stage.completionDate);
    const start = index === 0 ? new Date(stage.startingDate) : new Date(stages[index - 1].completionDate || stage.startingDate);
    const diffMs = end - start;
    if (diffMs < 0) return "Invalid";
    const diffDays = Math.floor(diffMs / (24 * 3600 * 1000));
    const remainingMs = diffMs % (24 * 3600 * 1000);
    const remainingHours = Math.floor(remainingMs / (3600 * 1000));
    const remainingSeconds = Math.floor((remainingMs % (3600 * 1000)) / 1000);
    const totalWorkingHours = diffDays * 8 + remainingHours;
    return `${totalWorkingHours} Hrs. (${remainingSeconds} Sec)`;
  };

  const parseDurationToHours = (duration) => {
    if (duration === "TBD" || duration === "Invalid") return 0;
    const match = duration.match(/(\d+) Hrs\. \(\d+ Sec\)/);
    return match ? parseInt(match[1]) || 0 : 0;
  };

  const calculateDifference = (stageDuration, plannedHrs) => {
    const durationHrs = parseDurationToHours(stageDuration);
    const planned = parseFloat(plannedHrs) || 0;
    const diff = planned - durationHrs;
    return diff >= 0
      ? { text: `+${diff.toFixed(1)} Hrs Reserve`, color: "#ccffcc" }
      : { text: `${diff.toFixed(1)} Hrs Short`, color: "#ff6666" };
  };

  const calculateProjectTiming = () => {
    if (!orderNumberDate || !dueDate) return "N/A";
    const start = new Date(orderNumberDate);
    const end = new Date(dueDate);
    const diffDays = Math.floor((end - start) / (1000 * 60 * 60 * 24));
    return `${diffDays} Days`;
  };

  const calculatePODaysActive = () => {
    if (!orderNumberDate) return "N/A";
    const start = new Date(orderNumberDate);
    const end = new Date(currentDate);
    const diffDays = Math.floor((end - start) / (1000 * 60 * 60 * 24));
    return `${diffDays} Days`;
  };

  const calculateProjectTimingProgress = () => {
    if (!orderNumberDate || !dueDate) return 0;
    const start = new Date(orderNumberDate);
    const end = new Date(dueDate);
    const now = new Date(currentDate);
    const totalMs = end - start;
    const elapsedMs = now - start;
    return totalMs > 0 ? Math.min(Math.max((elapsedMs / totalMs) * 100, 0), 100) : 0;
  };

  const handleStageChange = (index, field, value) => {
    const certainProcesses = [
      "Drawing",
      "Fabrication Drawing",
      "Scan Part Drawing",
      "Customer Drawing",
      "Rep Drawing",
    ];
    const manualStatusProcesses = [
      "Milling",
      "Turning",
      "Grinding",
      "Wire Cutting",
      "Fabrication",
    ];
    const newStages = [...stages];
    const oldStatus = newStages[index].status;

    if (
      field === "status" &&
      index === 0 &&
      value === "Completed" &&
      !project &&
      !workSheetNo
    ) {
      alert("Please enter a Work Sheet Number before marking the first process as Completed.");
      return;
    }

    if (field === "status" && newStages[index].process === "Sign Delivery Book") {
      if (value === "Completed" && !signDeliveryBookNo) {
        alert("Please enter a Delivery Book Number and press 'Enter' to set Completed status.");
        setPulseSignDeliveryBook(true);
        return;
      }
      if (value === "Completed") {
        newStages[index].completionDate = new Date().toISOString();
        newStages[index].stageDuration = calculateDuration(index, newStages);
        newStages[index].deliveryBookNo = signDeliveryBookNo;
      }
    } else if (field === "status" && newStages[index].process === "Site Instr. Signed Off") {
      if (value === "Completed" && !siteInstrSignedOffNo) {
        alert("Please enter a Site Instruction Number and press 'Enter' to set Completed status.");
        setPulseSiteInstrSignedOff(true);
        return;
      }
      if (value === "Completed") {
        newStages[index].completionDate = new Date().toISOString();
        newStages[index].stageDuration = calculateDuration(index, newStages);
        newStages[index].deliveryBookNo = siteInstrSignedOffNo;
      }
    }

    newStages[index][field] = value;

    if (field === "responsible") {
      const person = personnel.find((p) => p.name === value);
      newStages[index].cell = person?.cell || "";
      newStages.forEach((stage, i) => {
        if (stage.responsible === value && i !== index)
          stage.cell = newStages[index].cell;
      });
    } else if (field === "cell") {
      const responsible = newStages[index].responsible;
      newStages.forEach((stage) => {
        if (stage.responsible === responsible) stage.cell = value;
      });
    } else if (field === "plannedHrs") {
      let cleanedValue = value.replace(/[^\d.]/g, "");

      // Update the current stage
      newStages[index].plannedHrs = cleanedValue;

      // Auto-fill all "Quality Control" rows if this is a QC row
      if (newStages[index].process === "Quality Control") {
        newStages.forEach(stage => {
          if (stage.process === "Quality Control") {
            stage.plannedHrs = cleanedValue;
          }
        });
      }
    } else if (field === "process") {
      if (!["Milling", "Turning", "Wire Cutting", "Grinding"].includes(value)) {
        newStages[index].machine = "";
      } else {
        newStages[index].machine = value === "Wire Cutting" ? "OP110-WIRECUT.FANUC" :
          value === "Grinding" ? "OP330-CINCINATTI.HORZ.GRINDER" : "";
      }
    }

    const now = new Date().toISOString();
    if (field === "status") {
      if (
        newStages[index].process === "Invoiced" &&
        (value === "In Progress" || value === "Completed") &&
        !newStages[index].startingDate
      ) {
        newStages[index].startingDate = now;
      }

      if (
        index === 0 &&
        value === "In Progress" &&
        !newStages[0].startingDate
      ) {
        newStages[0].startingDate = now;
      }
      if (
        index > 0 &&
        ["Completed", "Drawing Reviewed", "Drawing not Reviewed", "Completed: QC Pass"].includes(newStages[index - 1].status) &&
        !newStages[index].startingDate
      ) {
        newStages[index].startingDate = now;
      }
      if (
        ["Completed", "Drawing Reviewed", "Drawing not Reviewed", "Completed: QC Pass"].includes(value) &&
        !["Completed", "Drawing Reviewed", "Drawing not Reviewed", "Completed: QC Pass", "Sign Delivery Book", "Site Instr. Signed Off"].includes(oldStatus)
      ) {
        newStages[index].completionDate = now;
        newStages[index].stageDuration = calculateDuration(index, newStages);

        if (newStages[index].process === "Invoiced" && value === "Completed") {
          setActualCompletionDate(newStages[index].startingDate.split("T")[0]);
        }

        if (["Completed", "Completed: QC Pass"].includes(value) && index < newStages.length - 1) {
          const nextStage = newStages[index + 1];
          const nextProcess = nextStage.process || "Next Stage";
          if (nextStage.responsible && nextStage.cell) {
            const message = `Hi ${nextStage.responsible}, re: WS${workSheetNo}, ${jobDescription}, ${newStages[index].process} is completed for ${customer}. Please start ${nextProcess}.`;
            window.open(getWhatsAppLink(nextStage.cell, message), "_blank");
          }

          // Automatically activate the next row to "In Progress" if applicable, excluding specific processes
          if (
            nextStage.status === "Not Started" &&
            !["Sign Delivery Book", "Site Instr. Signed Off"].includes(nextStage.process) &&
            !manualStatusProcesses.includes(nextStage.process)
          ) {
            nextStage.status = "In Progress";
            if (!nextStage.startingDate) {
              nextStage.startingDate = now;
            }
          }
        }
      }
      if (
        newStages[index].process === "Sign Delivery Book" &&
        value !== "Insert Del. No. Below"
      ) {
        setPulseSignDeliveryBook(false);
      }
      if (
        newStages[index].process === "Site Instr. Signed Off" &&
        value !== "Insert Site No. Below"
      ) {
        setPulseSiteInstrSignedOff(false);
      }
    }

    if (
      field === "process" &&
      !["Sign Delivery Book", "Site Instr. Signed Off"].includes(value) &&
      ["Insert Del. No. Below", "Insert Site No. Below"].includes(newStages[index].status)
    ) {
      if (newStages[index].status === "Insert Del. No. Below")
        setPulseSignDeliveryBook(false);
      if (newStages[index].status === "Insert Site No. Below")
        setPulseSiteInstrSignedOff(false);
    }

    setStages(newStages);
  };

  const removeStageAtIndex = (index) => {
    if (stages.length <= 1) {
      alert("Cannot remove the last stage. At least one stage is required.");
      return;
    }
    setStages((prevStages) => prevStages.filter((_, i) => i !== index));
  };

  const insertStageAfterIndex = (index) => {
    const newStage = {
      process: "",
      responsible: "",
      status: "Not Started",
      startingDate: "",
      stageDuration: "TBD",
      plannedHrs: "",
      completionDate: "",
      cell: "",
      deliveryBookNo: "",
      machine: "",
    };
    setStages((prevStages) => [
      ...prevStages.slice(0, index + 1),
      newStage,
      ...prevStages.slice(index + 1),
    ]);
  };

const saveProject = async (updatedStages = stages) => {
  console.log("saveProject called with projectId:", projectId);

  // BLOCK SAVE if job is archived
  if (initialProject?.status === "archived") {
    alert("This job is archived.\n\nYou cannot save changes here.\n\nUse the red X to close, or Unarchive (password protected) from the main wall.");
    return false;
  }

  const newProjectId = `${orderPrefix}${orderNumber}`;
  if (!orderNumber || orderNumber.trim() === "" || newProjectId.startsWith("TEMPORARY_ID")) {
    setValidationError("Cannot save project: Invalid or missing Order Number.");
    return false;
  }

  const duplicateError = await checkForDuplicates(newProjectId, workSheetNo, quoteNumber);
  if (duplicateError) {
    setValidationError(duplicateError);
    return false;
  }

  const projectStages = updatedStages.map((stage) => ({
    process: stage.process || "",
    responsible: stage.responsible || "",
    status: stage.status || "Not Started",
    startingDate: stage.startingDate || "",
    stageDuration: stage.stageDuration || "TBD",
    plannedHrs: stage.plannedHrs || "",
    completionDate: stage.completionDate || "",
    deliveryBookNo: stage.process === "Sign Delivery Book" ? stage.deliveryBookNo || signDeliveryBookNo || "" :
      stage.process === "Site Instr. Signed Off" ? stage.deliveryBookNo || siteInstrSignedOffNo || "" : "",
    machine: stage.machine || "",
  }));

  const projectData = {
    orderNumber: newProjectId,
    quoteNumber: quoteNumber || "",
    orderNumberDate: orderNumberDate || "",
    workSheetNo: `WS${workSheetNo}`,
    salesRep: salesRep || "",
    customer: customer || "",
    jobDescription: jobDescription || "",
    currentDate,
    dueDate: dueDate || "",
    firstDueDate: firstDueDate || "",
    actualCompletionDate: actualCompletionDate || "",
    stages: projectStages,
    status: "active",
    isSalesRepInputActive,
    selectedTemplate,
    selectedMachine: selectedMachine || "",
    poDate: project.poDate || "",
    fixtureDesign: project.fixtureDesign || [],
    manufacturingParts: project.manufacturingParts || [],
    buyOuts: project.buyOuts || [],
    fixtureAssembly: project.fixtureAssembly || [],
  };

  try {
    if (originalId && originalId !== newProjectId) {
      await deleteDoc(doc(db, "projects", originalId));
    }

    await setDoc(doc(db, "projects", newProjectId), projectData, { merge: true });
    setHasUnsavedChanges(false);
    console.log("Save successful for project:", newProjectId);
    return true;
  } catch (e) {
    console.error("Save failed:", e);
    alert(`Save failed: ${e.message}`);
    return false;
  }
};

  const handleDeliveryBookEnter = async () => {
    const validStages = ["Sign Delivery Book", "Site Instr. Signed Off"];
    const stageIndex = stages.findIndex(
      (stage) => validStages.includes(stage.process) && stage.status !== "Completed"
    );
    if (stageIndex === -1) {
      alert("No valid stage found for entry or the stage is already completed.");
      console.log("No valid stage found:", { stages, validStages });
      return;
    }
    const stageProcess = stages[stageIndex].process;
    const numberToSave = stageProcess === "Sign Delivery Book" ? signDeliveryBookNo : siteInstrSignedOffNo;

    if (!numberToSave || !selectedPersonnel) {
      alert(`Please enter a ${stageProcess} Number and select Personnel.`);
      console.log("Missing number or personnel:", { numberToSave, selectedPersonnel });
      setPulseSignDeliveryBook(stageProcess === "Sign Delivery Book" && !signDeliveryBookNo);
      setPulseSiteInstrSignedOff(stageProcess === "Site Instr. Signed Off" && !siteInstrSignedOffNo);
      return;
    }

    const now = new Date().toISOString();
    const newStages = [...stages];

    if (!newStages[stageIndex].startingDate) {
      newStages[stageIndex].startingDate = now;
    }

    newStages[stageIndex] = {
      ...newStages[stageIndex],
      status: "Completed",
      stageDuration: calculateDuration(stageIndex, newStages),
      responsible: selectedPersonnel,
      cell: personnel.find((p) => p.name === selectedPersonnel)?.cell || "",
      deliveryBookNo: numberToSave,
    };

    const selectedPerson = personnel.find((p) => p.name === selectedPersonnel);
    if (selectedPerson?.cell) {
      const message = `Hi ${selectedPersonnel}, re: WS${workSheetNo}, ${jobDescription}, ${stageProcess} #${numberToSave} signed.`;
      console.log("Sending WhatsApp message to:", selectedPerson.cell);
      window.open(getWhatsAppLink(selectedPerson.cell, message), "_blank");
    }

    if (stageIndex < newStages.length - 1) {
      const nextStage = newStages[stageIndex + 1];
      const nextProcess = nextStage.process || "Next Stage";
      if (nextStage.responsible && nextStage.cell) {
        const message = `Hi ${nextStage.responsible}, re: WS${workSheetNo}, ${jobDescription}, ${stageProcess} is completed. Please start ${nextProcess}.`;
        console.log("Sending WhatsApp message to next stage:", nextStage.responsible);
        window.open(getWhatsAppLink(nextStage.cell, message), "_blank");
      }
    }

    console.log("Updating stages:", JSON.stringify(newStages[stageIndex], null, 2));
    setStages(newStages);
    setShowStages(true);

    if (stageProcess === "Sign Delivery Book") {
      setSignDeliveryBookEntered(true);
      setPulseSignDeliveryBook(false);
    } else {
      setSiteInstrSignedOffEntered(true);
      setPulseSiteInstrSignedOff(false);
    }

    console.log("Calling saveProject from handleDeliveryBookEnter");
    const success = await saveProject(newStages);
    if (!success) {
      alert(`Failed to save ${stageProcess} Number. Please try again.`);
      console.log("Save failed in handleDeliveryBookEnter");
    } else {
      console.log("Project saved successfully after stage update");
    }
  };

  const getNextOrderNumber = async (prefix) => {
    try {
      const prefixes = prefix === "CUST.GA" ? ["CUST.GA", "CUST.GO-AHEAD"] : [prefix];
      let allNumbers = [];
      for (const p of prefixes) {
        const prefixStart = `${p}000`;
        const prefixEnd = `${p}999`;
        const q = query(
          collection(db, "projects"),
          where("orderNumber", ">=", prefixStart),
          where("orderNumber", "<=", prefixEnd)
        );
        const querySnapshot = await getDocs(q);
        console.log(`Prefix: ${p}, Docs:`, querySnapshot.docs.map(doc => ({ id: doc.id, orderNumber: doc.data().orderNumber })));
        const numbers = querySnapshot.docs
          .map((doc) => doc.data().orderNumber)
          .filter((orderNumber) => orderNumber && orderNumber.startsWith(p))
          .map((orderNumber) => {
            const num = parseInt(orderNumber.replace(p, ""), 10);
            return isNaN(num) ? 0 : num;
          });
        allNumbers = [...allNumbers, ...numbers];
      }
      console.log(`Prefix: ${prefix}, Numbers:`, allNumbers);
      const maxNumber = allNumbers.length > 0 ? Math.max(...allNumbers) : 0;
      const nextNumber = (maxNumber + 1).toString().padStart(3, "0");
      return nextNumber;
    } catch (error) {
      console.error(`Error fetching next number for ${prefix}:`, error);
      return "001";
    }
  };

  const handleOrderPrefixChange = async (e) => {
    const newPrefix = e.target.value;
    console.log("handleOrderPrefixChange triggered with:", newPrefix);
    setOrderPrefix(newPrefix);
    setValidationError("");

    const autoPrefixes = ["EXPT.EPR", "CUST.GA", "EXPT.MAC"];

    if (autoPrefixes.includes(newPrefix)) {
      try {
        const newOrderNumber = await getNextOrderNumber(newPrefix);
        console.log(`Setting orderNumber to: ${newOrderNumber}`);
        setOrderNumber(newOrderNumber);
        setOrderNumberDate(new Date().toISOString().split("T")[0]);
        setIsOrderNumberAutoGenerated(true);
      } catch (error) {
        console.error("Failed to generate order number:", error);
        setOrderNumber("001");
        setOrderNumberDate(new Date().toISOString().split("T")[0]);
        setIsOrderNumberAutoGenerated(true);
      }
    } else {
      if (isOrderNumberAutoGenerated) {
        setOrderNumber("");
        setOrderNumberDate("");
        setIsOrderNumberAutoGenerated(false);
      }
    }
  };

  const checkForDuplicates = async (newProjectId, workSheetNo, quoteNumber) => {
    try {
      const orderQuery = query(
        collection(db, "projects"),
        where("orderNumber", "==", newProjectId)
      );
      const orderSnapshot = await getDocs(orderQuery);
      if (!orderSnapshot.empty && orderSnapshot.docs[0].id !== originalId) {
        return `Order Number ${newProjectId} already exists. Please append a differentiator (e.g., -a, -b, -c) to avoid conflicts.`;
      }

      if (workSheetNo) {
        const wsQuery = query(
          collection(db, "projects"),
          where("workSheetNo", "==", `WS${workSheetNo}`)
        );
        const wsSnapshot = await getDocs(wsQuery);
        if (!wsSnapshot.empty && wsSnapshot.docs[0].id !== originalId) {
          return `Work Sheet Number WS${workSheetNo} already exists. Please append a suffix (e.g., -a, -b, -c) to avoid conflicts.`;
        }
      }

      if (quoteNumber) {
        const quoteQuery = query(
          collection(db, "projects"),
          where("quoteNumber", "==", quoteNumber)
        );
        const quoteSnapshot = await getDocs(quoteQuery);
        if (!quoteSnapshot.empty && quoteSnapshot.docs[0].id !== originalId) {
          return `Quote Number ${quoteNumber} already exists. Please append a suffix to avoid conflicts.`;
        }
      }

      return "";
    } catch (error) {
      console.error("Error checking duplicates:", error);
      return "An error occurred while checking for duplicates. Please try again.";
    }
  };

  const suggestDifferentiator = (value) => {
    const differentiators = ["-a", "-b", "-c", "-d", "-e"];
    let newValue = value;
    for (const diff of differentiators) {
      if (!newValue.includes(diff)) {
        newValue = `${value}${diff}`;
        return newValue;
      }
    }
    return newValue;
  };

  const applyStageTemplate = (templateName, templates) => {
    console.log("Apply stage template:", {
      templateName,
      currentStages: stages,
      selectedTemplate,
      processes: processes.map((p) => p.name),
      templateProcesses: templates[templateName] || [],
    });
    if (templateName === "Select Stage Template") {
      setShowStages(false);
      setSelectedTemplate("Select Stage Template");
      setStages([]);
      return;
    }
    setShowStages(true);
    setSelectedTemplate(templateName);
    const templateStages = templates[templateName] || [];
    let newStages = templateStages.map((templateStage) => {
      const existingStage = stages.find((s) => s.process === templateStage.process);
      const isValidProcess = processes.some((p) => p.name === templateStage.process) || templateStage.process === "Delivery Note-Customer";
      console.log("Validating process:", { process: templateStage.process, isValidProcess });
      return {
        process: isValidProcess ? templateStage.process : "",
        responsible: templateStage.responsible === "salesRep" ? salesRep || existingStage?.responsible || "" : existingStage?.responsible || templateStage.responsible || "",
        status: templateStage.process === "Sign Delivery Book" ? "Insert Del. No. Below" :
          templateStage.process === "Site Instr. Signed Off" ? "Insert Site No. Below" : existingStage?.status || "Not Started",
        startingDate: existingStage?.startingDate || "",
        stageDuration: existingStage?.stageDuration || "TBD",
        plannedHrs: existingStage?.plannedHrs || "",
        completionDate: existingStage?.completionDate || "",
        cell: existingStage?.cell || personnel.find((p) => p.name === (templateStage.responsible === "salesRep" ? salesRep : templateStage.responsible))?.cell || "",
        deliveryBookNo: existingStage?.deliveryBookNo || "",
        machine: existingStage?.machine || templateStage.machine || "",
      };
    });

    if (newStages.length > 0 && newStages[0].status === "Not Started" && !["Sign Delivery Book", "Site Instr. Signed Off"].includes(newStages[0].process)) {
      newStages[0].status = "In Progress";
      newStages[0].startingDate = new Date().toISOString();
    }

    console.log("New stages set:", newStages);
    setStages(newStages);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("handleSubmit called, stack:", new Error().stack);
	
	  if (isReadOnly) {
    alert("This job is archived.\nYou cannot make changes.");
    return;
  }

    if (!orderNumber || orderNumber.trim() === "") {
      setValidationError("Please enter a valid Order Number.");
      console.log("Validation failed: Order Number is empty");
      return;
    }

    const newProjectId = `${orderPrefix}${orderNumber}`;
    console.log("Calling saveProject from handleSubmit with projectId:", newProjectId);
    const success = await saveProject();
    if (success) onClose();
  };

  const handlePrint = () => window.print();

  const handleSaveAsPDF = () => {
    const doc = new jsPDF();
    const element = document.querySelector("#project-form");

    html2canvas(element, { scale: 2 }).then((canvas) => {
      const imgData = canvas.toDataURL("image/png");
      const imgProps = doc.getImageProperties(imgData);
      const pdfWidth = doc.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      doc.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
      doc.save(`project-${orderPrefix}${orderNumber}.pdf`);
    });
  };

  // ==================================================================
  // FINAL & PERFECT COLOUR LOGIC – EVERYTHING WORKS 100%
  // ==================================================================

  const isBrandNewProject = !originalId || originalId.startsWith("TEMPORARY_ID");

  const deliveryStageIndex = stages.findIndex(
    s => s.process === "Sign Delivery Book" || s.process === "Site Instr. Signed Off"
  );
  const deliveryStageExists = deliveryStageIndex !== -1;
  const invoicedRowExists = stages.length > 0 && stages[stages.length - 1]?.process === "Invoiced";
  const condition2Met = deliveryStageExists || invoicedRowExists;

  const indexToCheck = deliveryStageExists ? deliveryStageIndex : stages.length - 1;
  const allPreviousStagesCompleted =
    indexToCheck <= 0
      ? true
      : stages.slice(0, indexToCheck).every(s =>
          ["Completed", "Completed: QC Pass", "Drawing Reviewed", "Drawing not Reviewed"].includes(s.status)
        );

  const orderLower = (project.orderNumber || "").toLowerCase();
  const hasInvalidPO =
    orderLower.includes("epr") ||
    orderLower.includes("cust.ga") ||
    orderLower.includes("cust.go-ahead") ||
    orderLower.includes("cod");

  const hasWorkSheetNo = !!project.workSheetNo?.trim();

  const isMissingPO   = condition2Met && allPreviousStagesCompleted && hasInvalidPO && hasWorkSheetNo;    // Orange
  const isReadyWithPO = condition2Met && allPreviousStagesCompleted && !hasInvalidPO && hasWorkSheetNo;   // Blue

  // ONLY show yellow if it's a SAVED job missing WS or Due Date
  const showYellow = !isBrandNewProject && (!dueDate || !hasWorkSheetNo);

  const bandColor = isReadyWithPO ? "#add8e6" :                  // Blue
                    isMissingPO   ? "#ffcc99" :                  // Orange
                    selectedTemplate === "9 - Stock Supplied" ? "#f0e4ff" :
                    selectedTemplate === "6 - Machine Repairs" ? "#b2dfdb" :
                    showYellow ? "#ffffe0" :                     // Yellow only on saved jobs
                    dueDate >= currentDate ? "#d4edda" : "#ff6666"; // ← GREEN or RED here!

  const formAnimation = isReadyWithPO ? "pulseBlueBorder 2s infinite" :
                        isMissingPO   ? "pulseOrangeBorder 2s infinite" :
                        selectedTemplate === "9 - Stock Supplied" ? "pulsePurpleBorder 2s infinite" :
                        selectedTemplate === "6 - Machine Repairs" ? "pulseTealBorder 2s infinite" :
                        showYellow ? "pulseYellow 2s infinite" :
                        dueDate >= currentDate ? "pulseGreenBorder 2s infinite" :
                        "pulseRedBorder 2s infinite";

  const dragAnimation = isReadyWithPO ? "pulseBlue 2s infinite" :
                        isMissingPO   ? "pulseOrange 2s infinite" :
                        selectedTemplate === "9 - Stock Supplied" ? "pulsePurple 2s infinite" :
                        selectedTemplate === "6 - Machine Repairs" ? "pulseTeal 2s infinite" :
                        showYellow ? "pulseYellow 2s infinite" :
                        dueDate >= currentDate ? "pulseGreen 2s infinite" :
                        "pulseRed 2s infinite";

  return (
<div
  ref={formRef}
  id="project-form"
  style={{
    position: "absolute",
    left: `${position.x}%`,
    top: `${position.y}%`,
    background: "#fff",
    border: "1px solid black",
    boxShadow: `inset 0 0 0 3mm ${bandColor}`,
    outline: "1px solid black",
    outlineOffset: "-3mm",
    animation: formAnimation,
    borderRadius: "10px",
    zIndex: 10001,
	overflow: "hidden"          // ← add this
  }}
  onMouseMove={onDrag}
  onMouseUp={stopDrag}
  onMouseLeave={stopDrag}
  onTouchMove={onDrag}
  onTouchEnd={stopDrag}
  onClick={(e) => {
    e.persist();
    e.stopPropagation();
    console.log('Form click stopped bubbling');
  }}
>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", margin: "20px 20px 20px 20px" }}>
        <div style={{ margin: "0" }}>
          <select
            value={selectedMachine || "Select Machine"}
            onChange={(e) =>
              setSelectedMachine(e.target.value === "Select Machine" ? "" : e.target.value)
            }
            style={{
              padding: "5px 10px",
              border: "1px solid #999",
              borderRadius: "3px",
              backgroundColor: "#ffff66",
              animation: "pulseYellow 2s infinite",
              width: "175px",
              height: "30px",
              boxSizing: "border-box",
            }}
          >
            <option value="Select Machine">Select Machine</option>
            {machines.map((machine) => (
              <option key={machine.id} value={machine.name}>
                {machine.name}
              </option>
            ))}
          </select>
          <div style={{ fontSize: "13px", color: "#666", marginBottom: "-15px", marginTop: "3px" }}>
            For Machine Maintenance Only
          </div>
        </div>
        <h2 style={{ margin: "0", textAlign: "center", flex: "1" }}>
          Project Tracker - Job Card
        </h2>
        <div style={{ margin: "0", textAlign: "right" }}>
          <select
            value={selectedProgressReport}
            onChange={(e) => setSelectedProgressReport(e.target.value)}
            disabled={!isProgressReportEnabled}
            style={{
              padding: "5px 10px",
              border: "1px solid #999",
              borderRadius: "3px",
              backgroundColor: isProgressReportEnabled ? "#ffff66" : "#e0e0e0",
              animation: isProgressReportEnabled ? "pulseYellow 2s infinite" : "none",
              width: "180px",
              height: "30px",
              boxSizing: "border-box",
            }}
          >
            <option value="Select Progress Report">Select Progress Report</option>
            <option value="1 - Job Card">1 - Job Card</option>
            <option value="2 - Jigs & Fixtures">2 - Jigs & Fixtures</option>
          </select>
          <div style={{ fontSize: "13px", color: "#666", marginBottom: "-15px", marginTop: "3px" }}>
            Select Report Type
          </div>
        </div>
      </div>
  <div
    style={{
      width: "96%",
      height: "50px",
      background: validationError ? "#ffcccc" : bandColor,
      cursor: "grabbing",   // or "grab" if you prefer fixed
      textAlign: "center",
      lineHeight: "50px",
      fontSize: "12px",
      fontWeight: "300",
      color: validationError ? "#333" : "#666",
      margin: "5px auto 10px auto",
      border: validationError ? "1px solid #ff6666" : "1px solid #999",
      borderRadius: "8px",
      animation: validationError ? "pulseRedInput 2s infinite" : dragAnimation,
    }}
    onMouseDown={(e) => {
      e.persist();
      e.stopPropagation();
      startDrag(e);
    }}
    onTouchStart={(e) => {
      e.persist();
      e.stopPropagation();
      startDrag(e);
    }}
  >
  {validationError ? validationError : "Drag Bar"}
</div>
      <div style={{ margin: "0 20px 10px 20px" }}>
        <ProjectFormSub1
          orderPrefix={orderPrefix}
          currentDate={currentDate}
          orderNumberDate={orderNumberDate}
          dueDate={dueDate}
          firstDueDate={firstDueDate}
          calculatePODaysActive={calculatePODaysActive}
          calculateProjectTiming={calculateProjectTiming}
          calculateProjectTimingProgress={calculateProjectTimingProgress}
          selectedTemplate={selectedTemplate}
          bandColor={bandColor}
          isReadyWithPO={isReadyWithPO}
          isMissingPO={isMissingPO}
        />
      </div>
      <div style={{ padding: "10px 20px 20px 20px" }}>
        <form id="projectForm" onSubmit={handleSubmit}>
          <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "-43px" }}>
            <ProjectFormSub2
              quoteNumber={quoteNumber}
              orderPrefix={orderPrefix}
              orderNumber={orderNumber}
              orderNumberDate={orderNumberDate}
              workSheetNo={workSheetNo}
              isSalesRepInputActive={isSalesRepInputActive}
              project={project}
              handleQuoteNumberChange={(e) => setQuoteNumber(e.target.value)}
              handleOrderPrefixChange={handleOrderPrefixChange}
              handleOrderNumberChange={(e) => {
                setOrderNumber(e.target.value);
                if (e.target.value && !orderNumberDate)
                  setOrderNumberDate(new Date().toISOString().split("T")[0]);
                setIsOrderNumberAutoGenerated(false);
                setValidationError("");
              }}
              handleWorkSheetNoChange={(e) =>
                setWorkSheetNo(e.target.value.replace(/\D/g, ""))
              }
            />
            <ProjectFormSub3
              salesRep={salesRep}
              currentDate={currentDate}
              customer={customer}
              jobDescription={jobDescription}
              messageCount={messageCount}
              project={project}
              personnel={personnel}
              customers={customers}
              handleSalesRepChange={(e) => {
                setSalesRep(e.target.value);
                if (e.target.value) triggerWhatsApp(e.target.value);
              }}
              setCustomer={setCustomer}
              setJobDescription={setJobDescription}
              setShowFeedbackModal={setShowFeedbackModal}
            />
            <ProjectFormSub4
              actualCompletionDate={actualCompletionDate}
              dueDate={dueDate}
              isSalesRepInputActive={isSalesRepInputActive}
              handlePrint={handlePrint}
              onClose={onClose}
              setDueDate={setDueDate}
              handleSaveAsPDF={handleSaveAsPDF}
			  hasUnsavedChanges={hasUnsavedChanges}   // ← add this line
			  onSave={saveProject}   // ← add this line
            />
          </div>
          <ProjectFormSub5
            selectedTemplate={selectedTemplate}
            isSalesRepInputActive={isSalesRepInputActive}
            showQuotingForm={showQuotingForm}
            applyStageTemplate={applyStageTemplate}
            toggleSalesRepInput={() => setIsSalesRepInputActive((prev) => !prev)}
            setShowQuotingForm={setShowQuotingForm}
            setShowFeedbackModal={setShowFeedbackModal}
            messageCount={messageCount}
            salesRep={salesRep}
            orderPrefix={orderPrefix}
            orderNumber={orderNumber}
          />
          {showStages && (
            <>
              <ProjectFormSub6
                stages={stages}
                processes={processes}
                personnel={personnel}
                machines={machines}
                calculateDifference={calculateDifference}
                handleStageChange={handleStageChange}
                removeStageAtIndex={removeStageAtIndex}
                insertStageAfterIndex={insertStageAfterIndex}
                projectId={projectId}
                workSheetNo={`WS${workSheetNo}`}
              />
              {console.log("ProjectForm passing workSheetNo:", `WS${workSheetNo}`)}
              <ProjectFormSub7
                signDeliveryBookNo={signDeliveryBookNo}
                setSignDeliveryBookNo={setSignDeliveryBookNo}
                siteInstrSignedOffNo={siteInstrSignedOffNo}
                setSiteInstrSignedOffNo={setSiteInstrSignedOffNo}
                selectedPersonnel={selectedPersonnel}
                setSelectedPersonnel={setSelectedPersonnel}
                signDeliveryBookEntered={signDeliveryBookEntered}
                siteInstrSignedOffEntered={siteInstrSignedOffEntered}
                pulseSignDeliveryBook={pulseSignDeliveryBook}
                pulseSiteInstrSignedOff={pulseSiteInstrSignedOff}
                personnel={personnel}
                addStage={() =>
                  setStages((prev) => [
                    ...prev.slice(0, -1),
                    {
                      process: "",
                      responsible: "",
                      status: "Not Started",
                      cell: "",
                      startingDate: "",
                      stageDuration: "TBD",
                      plannedHrs: "",
                      completionDate: "",
                      deliveryBookNo: "",
                      machine: "",
                    },
                    prev[prev.length - 1],
                  ])
                }
                removeStage={() =>
                  stages.length > 2
                    ? setStages((prev) => prev.slice(0, -2).concat(prev.slice(-1)))
                    : alert(
                        "Cannot remove the last two stages. 'Quote Auth&Submit' and 'Invoiced' are required."
                      )
                }
                handleDeliveryBookEnter={handleDeliveryBookEnter}
                addStageButtonRef={addStageButtonRef}
                stages={stages}
                stageProgressPercentage={stageProgressPercentage}
              />
            </>
          )}
        </form>
        {showFeedbackModal && (
          <FeedbackCommentsDelays
            onClose={() => {
              setShowFeedbackModal(false);
              fetchMessageAsync();
            }}
            projectId={projectId}
            workSheetNo={`WS${workSheetNo}`}
          />
        )}
{showQuotingForm && (
  <QuotingForm
    onClose={() => setShowQuotingForm(false)}
    selectedTemplate={selectedTemplate}
    stages={stages}
    onStagesUpdate={setStages}
    onTemplateChange={setSelectedTemplate}  // sync template selection back to ProjectForm
    orderPrefix={orderPrefix}
    orderNumber={orderNumber}
    workSheetNo={workSheetNo}
    bandColor={bandColor}
  />
)}
        {selectedProgressReport !== "Select Progress Report" && (
          <>
            {selectedProgressReport === "1 - Job Card" && (
              <ProjectFormProgressReport
                option={selectedProgressReport}
                project={{
                  orderPrefix,
                  orderNumber,
                  stages,
                  jobDescription,
                  workSheetNo: `WS${workSheetNo}`,
                  selectedTemplate,
                  customer,
                  salesRep,
                  currentDate,
                  dueDate,
                }}
              />
            )}
            {selectedProgressReport === "2 - Jigs & Fixtures" && (
              <ProjectFormDetailedCheckList
                option={selectedProgressReport}
                project={project}
                updateProject={(updatedProject) => setProject({ ...project, ...updatedProject })}
              />
            )}
          </>
        )}
      </div>
<style>{`
  @keyframes pulse { 0% { opacity: 1; } 50% { opacity: 0.8; } 100% { opacity: 1; } }
  @keyframes pulseGreen { 0% { background-color: #d4edda; } 50% { background-color: #c8e6c9; } 100% { background-color: #d4edda; } }
  @keyframes pulseRed { 0% { background-color: #ff6666; } 50% { background-color: #ff9999; } 100% { background-color: #ff6666; } }
  @keyframes pulseGreenBorder { 0% { box-shadow: inset 0 0 0 3mm #d4edda; } 50% { box-shadow: inset 0 0 0 3mm #c8e6c9; } 100% { box-shadow: inset 0 0 0 3mm #d4edda; } }
  @keyframes pulseRedBorder { 0% { box-shadow: inset 0 0 0 3mm #ff6666; } 50% { box-shadow: inset 0 0 0 3mm #ff9999; } 100% { box-shadow: inset 0 0 0 3mm #ff6666; } }
  @keyframes pulseYellow { 0% { background-color: #ffff66; } 50% { background-color: #f5f5a3; } 100% { background-color: #ffff66; } }
  @keyframes pulseRedInput { 0% { background-color: #ffcccc; } 50% { background-color: #ff9999; } 100% { background-color: #ffcccc; } }
  @keyframes pulsePurple { 0% { background-color: #f0e4ff; } 50% { background-color: #e8d9ff; } 100% { background-color: #f0e4ff; } }
  @keyframes pulsePurpleBorder { 0% { box-shadow: inset 0 0 0 3mm #f0e4ff; } 50% { box-shadow: inset 0 0 0 3mm #e8d9ff; } 100% { box-shadow: inset 0 0 0 3mm #f0e4ff; } }
  @keyframes pulseTeal { 0% { background-color: #b2dfdb; } 50% { background-color: #a3d7d2; } 100% { background-color: #b2dfdb; } }
  @keyframes pulseTealBorder { 0% { box-shadow: inset 0 0 0 3mm #b2dfdb; } 50% { box-shadow: inset 0 0 0 3mm #a3d7d2; } 100% { box-shadow: inset 0 0 0 3mm #b2dfdb; } }
  @keyframes pulseOrange { 0% { background-color: #ffcc99; } 50% { background-color: #ffd2a8; } 100% { background-color: #ffcc99; } }
  @keyframes pulseOrangeBorder { 0% { box-shadow: inset 0 0 0 3mm #ffcc99; } 50% { box-shadow: inset 0 0 0 3mm #ffd2a8; } 100% { box-shadow: inset 0 0 0 3mm #ffcc99; } }
  @keyframes pulseBlue { 0% { background-color: #add8e6; } 50% { background-color: #b9daea; } 100% { background-color: #add8e6; } }
  @keyframes pulseBlueBorder { 0% { box-shadow: inset 0 0 0 3mm #add8e6; } 50% { box-shadow: inset 0 0 0 3mm #b9daea; } 100% { box-shadow: inset 0 0 0 3mm #add8e6; } }

  #project-form, #project-form * { 
    transform: none !important; 
  }

  /* Strong attempt to hide default browser close X */
  #project-form {
    -webkit-app-region: no-drag !important;
    overflow: hidden !important;
  }

  @media only screen and (max-width: 767px) {
    #project-form {
      width: 100vw !important;
      max-width: 100vw !important;
      min-width: 100vw !important;
      left: 0 !important;
      margin: 0 auto !important;
      box-sizing: border-box !important;
      overflow-x: scroll !important;
      overflow-y: auto !important;
      padding: 0 0 !important;
    }

    #project-form > div,
    #project-form form,
    #project-form table {
      min-width: 900px !important;
      width: auto !important;
      box-sizing: border-box !important;
      white-space: nowrap !important;
    }

    #project-form table {
      table-layout: fixed !important;
    }

    #project-form tr,
    #project-form td,
    #project-form th {
      white-space: nowrap !important;
      overflow: hidden !important;
    }

    #project-form input,
    #project-form select {
      min-width: auto !important;
      font-size: 12px !important;
      padding: 3px !important;
    }
  }

  @media print {
    body { margin: 0; }
    #project-form {
      position: static !important;
      width: 900px !important;
      margin: 10px auto !important;
      padding: 0 !important;
      visibility: visible !important;
      box-shadow: none !important;
      border: 1px solid #000 !important;
      transform: none !important;
    }
    #project-form * {
      visibility: visible !important;
      animation: none !important;
      transform: none !important;
    }
    #project-form input, #project-form select, #project-form span, #project-form button {
      border: 1px solid #000 !important;
      color: #000 !important;
    }
    #project-form [style*="display: none"], #project-form [style*="display:none"] { display: block !important; }
    #project-form button[title="Remove Stage"], #project-form button[title="Insert stage after this"] { display: none !important; }
  }
`}</style>
    </div>
  );
}

ProjectForm.propTypes = {
  onClose: PropTypes.func.isRequired,
  project: PropTypes.shape({
    id: PropTypes.string,
    orderNumber: PropTypes.string,
    quoteNumber: PropTypes.string,
    orderNumberDate: PropTypes.string,
    workSheetNo: PropTypes.string,
    salesRep: PropTypes.string,
    customer: PropTypes.string,
    jobDescription: PropTypes.string,
    dueDate: PropTypes.string,
    actualCompletionDate: PropTypes.string,
    stages: PropTypes.arrayOf(
      PropTypes.shape({
        process: PropTypes.string,
        responsible: PropTypes.string,
        status: PropTypes.string,
        startingDate: PropTypes.string,
        stageDuration: PropTypes.string,
        plannedHrs: PropTypes.string,
        completionDate: PropTypes.string,
        deliveryBookNo: PropTypes.string,
        machine: PropTypes.string,
      })
    ),
    isSalesRepInputActive: PropTypes.bool,
    selectedTemplate: PropTypes.string,
    selectedMachine: PropTypes.string,
  }),
  processes: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string,
    })
  ).isRequired,
  personnel: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string,
      cell: PropTypes.string,
    })
  ).isRequired,
  customers: PropTypes.arrayOf(PropTypes.string).isRequired,
};

export default ProjectForm;